// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMgj_UD2WiqMe0RNxlWq9BRg3e3yWtI8',
    appId: '1:132623252457:web:81b97786bbe07b14eca978',
    messagingSenderId: '132623252457',
    projectId: 'hire-assist-73bd2',
    authDomain: 'hire-assist-73bd2.firebaseapp.com',
    storageBucket: 'hire-assist-73bd2.firebasestorage.app',
    measurementId: 'G-RK5KPXFBPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKqotqtJTrezPvhn-UEmdXZdYzWdNgQI',
    appId: '1:132623252457:android:dc7aad6e793db3a0eca978',
    messagingSenderId: '132623252457',
    projectId: 'hire-assist-73bd2',
    storageBucket: 'hire-assist-73bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWGATHhvXvIBMFTmIfZ-NKEvY4nf8x9o',
    appId: '1:132623252457:ios:9e44afeb735f6451eca978',
    messagingSenderId: '132623252457',
    projectId: 'hire-assist-73bd2',
    storageBucket: 'hire-assist-73bd2.firebasestorage.app',
    iosBundleId: 'com.kalpesh.hireassist.hireAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKWGATHhvXvIBMFTmIfZ-NKEvY4nf8x9o',
    appId: '1:132623252457:ios:9e44afeb735f6451eca978',
    messagingSenderId: '132623252457',
    projectId: 'hire-assist-73bd2',
    storageBucket: 'hire-assist-73bd2.firebasestorage.app',
    iosBundleId: 'com.kalpesh.hireassist.hireAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMgj_UD2WiqMe0RNxlWq9BRg3e3yWtI8',
    appId: '1:132623252457:web:2c77274052256250eca978',
    messagingSenderId: '132623252457',
    projectId: 'hire-assist-73bd2',
    authDomain: 'hire-assist-73bd2.firebaseapp.com',
    storageBucket: 'hire-assist-73bd2.firebasestorage.app',
    measurementId: 'G-H0Z4BXERS0',
  );

}